GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjgxMTgzMTYzfQ.BHGyQzCLFfm8ARGLtwQtK7cTSj_LPO4VMVvuNsKEkUE
###

GET http://localhost:3001/users

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "Joe",
    "password": "password"
}

###

POST http://localhost:3001/users/login
Content-Type: application/json

{
    "name": "Joe",
    "password": "password"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "Joe"
}